framework:
  messenger:
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      symfonyAsync:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queue_name: default
          use_notify: true
        retry_strategy:
          delay: 1000 # 1 sec
          max_retries: 3
          multiplier: 5
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer
        options:
          queue_name: app
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          delay: 1000 # 1 sec
          max_retries: 3
          multiplier: 5
      failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default: [ ]
      command.bus:
        middleware:
          - App\Middleware\MilpacUpdateMessageMiddleware
      event.bus:
        default_middleware: allow_no_handlers

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: symfonyAsync
      Symfony\Component\Notifier\Message\ChatMessage: symfonyAsync
      Symfony\Component\Notifier\Message\SmsMessage: symfonyAsync
      'App\Message\*': async

      # Route your messages to the transports
      # 'App\Message\YourMessage': async




when@test:
  framework:
    messenger:
      transports:
        async: 'in-memory://'
